# Generated by Django 3.2 on 2021-04-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_modifiers_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.section'),
        ),
    ]
