# Generated by Django 3.2 on 2021-04-27 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
    ]
